name: Compile Sketches and Update BOM

# Run compile at 10:26 every night.
on:
  push:
  pull_request:
  schedule:
    - cron: '26 22 * * *'
  
jobs:
  compile-sketches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Change secret file's name
        run: sed -i "s/arduino_secrets/example_arduino_secrets/" /home/runner/work/WMATA_PCB/WMATA_PCB/test_code/test_code.ino
      # See: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketches
        uses: arduino/compile-sketches@v1
        with:
          platforms: |
            - source-url: http://arduino.esp8266.com/stable/package_esp8266com_index.json
              name: esp8266:esp8266
          fqbn: esp8266:esp8266:nodemcuv2
          sketch-paths: |
            - test_code
            - dev_code_snippits
          libraries: |
            - name: ArduinoJson
            - name: Adafruit LED Backpack Library
            - source-path: inc
            - source-path: ./
      # After succesful compilation, update the BOM with the latest dependencies installed by Arduino Compiler (from source), and validate the update against BOM schema.
      - name: Validate BOM - Setup GO
        uses: actions/setup-go@v2
      - name: Update BOM
        run: bash ./bom_update.sh
      - name: Validate BOM
        run: |
          go get github.com/neilpa/yajsv
          /home/runner/go/bin/yajsv -s cyclonedx-schema-1_2.json bom.json
      - name: Push BOM to Repo
        run: |
          git config user.email "BOM_Update_Bot@github.com"
          git config user.name "BOM Update / Sketch Compile Action"
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/LArkema/WMATA_PCB.git
          if git status | grep "bom.json"
          then
            git add bom.json
            git commit -m "Update Dependency Versions in BOM"
            git push origin main
          fi
