name: Compile Sketches

# Run compile at 10:26 every night.
on:
  push:
  pull_request:
  schedule:
    - cron: '26 22 * * *'
  
jobs:
  compile-sketches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Change secret file's name
        run: sed -i "s/arduino_secrets/example_arduino_secrets/" /home/runner/work/WMATA_PCB/WMATA_PCB/test_code/test_code.ino
      # See: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketches
        uses: arduino/compile-sketches@v1
        with:
          platforms: |
            - source-url: http://arduino.esp8266.com/stable/package_esp8266com_index.json
              name: esp8266:esp8266
          fqbn: esp8266:esp8266:nodemcuv2
          sketch-paths: |
            - test_code
            - dev_code_snippits
          libraries: |
            - name: ArduinoJson
            - source-path: inc
            - source-path: ./
