name: Compile Sketches

# Run compile at 10:26 every night.
on:
  push:
  pull_request:
  schedule:
    - cron: '26 22 * * *'
  
jobs:
  compile-sketches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      # See: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketches
        uses: arduino/compile-sketches@v1.0.1
        with:
          platforms: |
            - source-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
              name: esp8266:esp8266
          fqbn: esp8266:esp8266:nodemcuv2
          sketch-paths: |
            - DCTransistor
          libraries: |
            - name: ArduinoJson
            - name: Adafruit NeoPixel
            - name: WiFiManager
            - source-path: ./
      # BOM update moved to separate workflow