name: Lint Sketches

on: 
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/arduino-lint-action@v1
        with:
          path: test_code
          library-manager: update
          project-type: sketch
          report-file: lint-report.json
          verbose: true
