name: Lint Sketches

on: 
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Arduino Lint
        uses: arduino/arduino-lint-action@v1
        with:
          path: test_code
          project-type: sketch
          report-file: lint-report.json
          verbose: true
      - name: "Push changes back to repo"
        run: |
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/LArkema/WMATA_PCB.git
          git add .
          git commit -m "Update lint report"
          git push origin main
